//Dinh nghia type cho cac actions

const START = "START";
const START_FINISHED = "START_FINISHED";

const STOP = "STOP";

const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";

const LOGOUT = "LOGOUT";
const LOGOUT_SUCCESS = "LOLOGOUT_SUCCESSGOUT";
const LOGOUT_FAILED = "LOGOUT_FAILED";

const FETCH_CONTACTS = "FETCH_CONTACTS";
const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
const FETCH_CONTACTS_FAILED = "FETCH_CONTACTS_FAILED";

export default {
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGOUT,
	LOGOUT_SUCCESS,
	LOGOUT_FAILED,
	START,
	START_FINISHED,
	FETCH_CONTACTS,
	FETCH_CONTACTS_SUCCESS,
	FETCH_CONTACTS_FAILED,
	STOP
}
