//Dinh nghia type cho cac actions

const START = "START";
const START_FINISHED = "START_FINISHED";

const STOP = "STOP";

const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";

const LOGOUT = "LOGOUT";
const LOGOUT_FINISHED = "LOGOUT_FINISHED";

const FETCH_CONTACTS = "FETCH_CONTACTS";
const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
const FETCH_CONTACTS_FAILED = "FETCH_CONTACTS_FAILED";

const LOAD_MORE_CONTACTS = "LOAD_MORE_CONTACTS";
const LOAD_MORE_CONTACTS_SUCCESS = "LOAD_MORE_CONTACTS_SUCCESS";
const LOAD_MORE_CONTACTS_FAILED = "LOAD_MORE_CONTACTS_FAILED";

export default {
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGOUT,
	LOGOUT_FINISHED,
	START,
	START_FINISHED,
	FETCH_CONTACTS,
	FETCH_CONTACTS_SUCCESS,
	FETCH_CONTACTS_FAILED,
	STOP,
	LOAD_MORE_CONTACTS,
	LOAD_MORE_CONTACTS_SUCCESS,
	LOAD_MORE_CONTACTS_FAILED
}
